### PR TITLE
updated to Pure MLDSA mode with 512-bit input msg

### PR DESCRIPTION
**Pull request by mojtaba-bisheh**

### CODE REVIEW

**Comment by brainhub** [comment]
Could you please comment how this relates to #54? I would expect to see pure ML-DSA implemented with "external mu" interface

**Comment by mojtaba-bisheh** [comment]
> Could you please comment how this relates to #54? I would expect to see pure ML-DSA implemented with "external mu" interface

AdamsBridge doesn't support ExternalMu variant. This is pure MLDSA where the message size is limited to 512 bits based on Calitpra use model.

**Comment by brainhub** [comment]
Is the plan to move away from pre-hash ML-DSA to the one you described (fixed 512-bit message with pure ML-DSA)? 

(Currently HW spec only lists prehash variant of ML-DSA)

**Comment by mojtaba-bisheh** [comment]
> Is the plan to move away from pre-hash ML-DSA to the one you described (fixed 512-bit message with pure ML-DSA)?
> 
> (Currently HW spec only lists prehash variant of ML-DSA)

yes, I've filed an issue to update spec accordingly. 
https://github.com/chipsalliance/adams-bridge/issues/57

**Review by ekarabu — APPROVED** [review]

**Pull request merged**
